version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager
    restart: always
    ports:
      - 80:80
      - 443:443
      - 81:81
    env_file:
      - ./config/npm.env
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    network_mode: host
